	QBShared = QBShared or {}
QBShared.Items = {

	-- jim-mining stuff
	["stone"] 		 	 			 = {["name"] = "stone",           				["label"] = "Stone",	 				["weight"] = 2000, 	    ["type"] = "item", 		["image"] = "stone.png", 				["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "Stone woo"},

	["uncut_emerald"] 				 = {["name"] = "uncut_emerald", 			  	["label"] = "Uncut Emerald", 			["weight"] = 100, 		["type"] = "item", 		["image"] = "uncut_emerald.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A rough Emerald"},
	["uncut_ruby"] 					 = {["name"] = "uncut_ruby", 			  	  	["label"] = "Uncut Ruby", 				["weight"] = 100, 		["type"] = "item", 		["image"] = "uncut_ruby.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A rough Ruby"},
	["uncut_diamond"] 				 = {["name"] = "uncut_diamond", 			  	["label"] = "Uncut Diamond", 			["weight"] = 100, 		["type"] = "item", 		["image"] = "uncut_diamond.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A rough Diamond"},
	["uncut_sapphire"] 				 = {["name"] = "uncut_sapphire", 			  	["label"] = "Uncut Sapphire", 			["weight"] = 100, 		["type"] = "item", 		["image"] = "uncut_sapphire.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A rough Sapphire"},

	["uncut_amethyst"] 				 = {["name"] = "uncut_amethyst", 			  	["label"] = "Uncut Amethyst", 			["weight"] = 100, 		["type"] = "item", 		["image"] = "uncut_amethyst.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A rough Amethyst"},
	["uncut_citrine"] 				 = {["name"] = "uncut_citrine", 			  	["label"] = "Uncut Citrine", 			["weight"] = 100, 		["type"] = "item", 		["image"] = "uncut_citrine.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A rough Citrine"},
	["uncut_garnet"] 				 = {["name"] = "uncut_garnet", 			  	    ["label"] = "Uncut Garnet", 			["weight"] = 100, 		["type"] = "item", 		["image"] = "uncut_garnet.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A rough Garnet"},
	["uncut_onyx"] 		     		 = {["name"] = "uncut_onyx", 			     	["label"] = "Uncut Onyx", 			    ["weight"] = 100, 		["type"] = "item", 		["image"] = "uncut_onyx.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A rough Onyx"},
	["uncut_peridot"] 				 = {["name"] = "uncut_peridot", 			  	["label"] = "Uncut Peridot", 			["weight"] = 100, 		["type"] = "item", 		["image"] = "uncut_peridot.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A rough Peridot"},
	["uncut_tigereye"] 				 = {["name"] = "uncut_tigereye", 		  	  	["label"] = "Uncut Tigers Eye", 		["weight"] = 100, 		["type"] = "item", 		["image"] = "uncut_tigereye.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A rough Tiger`s Eye"},
	["uncut_topaz"] 				 = {["name"] = "uncut_topaz", 			    	["label"] = "Uncut Topaz", 			    ["weight"] = 100, 		["type"] = "item", 		["image"] = "uncut_topaz.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A rough Topaz"},

	["emerald"] 					 = {["name"] = "emerald", 			  	  		["label"] = "Emerald", 					["weight"] = 100, 		["type"] = "item", 		["image"] = "emerald.png", 				["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A Emerald that shimmers"},
	["ruby"] 						 = {["name"] = "ruby", 			  	  			["label"] = "Ruby", 					["weight"] = 100, 		["type"] = "item", 		["image"] = "ruby.png", 				["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A Ruby that shimmers"},
	["diamond"] 					 = {["name"] = "diamond", 			  	  		["label"] = "Diamond", 					["weight"] = 100, 		["type"] = "item", 		["image"] = "diamond.png", 				["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A Diamond that shimmers"},
	["sapphire"] 					 = {["name"] = "sapphire", 			  	  		["label"] = "Sapphire",					["weight"] = 100, 		["type"] = "item", 		["image"] = "sapphire.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A Sapphire that shimmers"},

	["amethyst"] 					 = {["name"] = "amethyst", 			  	  		["label"] = "Amethyst", 				["weight"] = 100, 		["type"] = "item", 		["image"] = "amethyst.png", 				["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A Amethyst that shimmers"},
	["citrine"] 					 = {["name"] = "citrine", 			  	 		["label"] = "Citrine", 					["weight"] = 100, 		["type"] = "item", 		["image"] = "citrine.png", 				["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A Citrine that shimmers"},
	["garnet"] 				 		 = {["name"] = "garnet", 			  	  		["label"] = "Garnet", 					["weight"] = 100, 		["type"] = "item", 		["image"] = "garnet.png", 				["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A Garnet that shimmers"},
	["onyx"] 						 = {["name"] = "onyx", 			  	  			["label"] = "Onyx",						["weight"] = 100, 		["type"] = "item", 		["image"] = "onyx.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A Onyx that shimmers"},
	["peridot"] 					 = {["name"] = "peridot", 			  	  		["label"] = "Peridot", 					["weight"] = 100, 		["type"] = "item", 		["image"] = "peridot.png", 				["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A Peridot that shimmers"},
	["tigereye"] 					 = {["name"] = "tigereye", 			  	  		["label"] = "Tiger`s Eye", 				["weight"] = 100, 		["type"] = "item", 		["image"] = "tigereye.png", 				["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A Tiger`s Eye that shimmers"},
	["topaz"] 						 = {["name"] = "topaz", 			  	  		["label"] = "Topaz", 					["weight"] = 100, 		["type"] = "item", 		["image"] = "topaz.png", 				["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A Topaz that shimmers"},

	["gold_ring"] 					 = {["name"] = "gold_ring", 			  	  	["label"] = "Gold Ring", 				["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_ring.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["diamond_ring"] 				 = {["name"] = "diamond_ring", 			  	  	["label"] = "Diamond Ring", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "diamond_ring.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["ruby_ring"] 					 = {["name"] = "ruby_ring", 			  	  	["label"] = "Ruby Ring", 				["weight"] = 200, 		["type"] = "item", 		["image"] = "ruby_ring.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["sapphire_ring"] 				 = {["name"] = "sapphire_ring", 			  	["label"] = "Sapphire Ring", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "sapphire_ring.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["emerald_ring"] 				 = {["name"] = "emerald_ring", 			  	  	["label"] = "Emerald Ring", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "emerald_ring.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},

	["amethyst_ring"] 				 = {["name"] = "amethyst_ring", 		  	  	["label"] = "Amethyst Ring", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_ring_amethyst.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["citrine_ring"] 				 = {["name"] = "citrine_ring", 			  	  	["label"] = "Citrine Ring", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_ring_citrine.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["garnet_ring"] 				 = {["name"] = "garnet_ring", 				  	["label"] = "Garnet Ring", 				["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_ring_garnet.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["onyx_ring"] 				 	 = {["name"] = "onyx_ring", 			  	  	["label"] = "Onyx Ring", 				["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_ring_onyx.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["peridot_ring"] 				 = {["name"] = "peridot_ring", 			  	  	["label"] = "Peridot Ring", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_ring_peridot.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["tigereye_ring"] 				 = {["name"] = "tigereye_ring", 			  	["label"] = "Tiger`s Eye Ring", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_ring_tigerseye.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["topaz_ring"] 					 = {["name"] = "topaz_ring", 			  		["label"] = "Topaz Ring", 				["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_ring_topaz.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},

	["rainbow_ring"] 				 = {["name"] = "rainbow_ring", 			  	  	["label"] = "Rainbow Ring", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "rainbowring.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["rainbow_ring_silver"] 				 = {["name"] = "rainbow_ring_silver", 			  	  	["label"] = "Silver Rainbow Ring", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_ring_rainbow.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},

	["silver_ring"] 				 = {["name"] = "silver_ring", 			  		["label"] = "Silver Ring", 				["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_ring.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["diamond_ring_silver"] 		 = {["name"] = "diamond_ring_silver", 		  	["label"] = "Diamond Ring Silver", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "diamond_ring_silver.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["ruby_ring_silver"] 			 = {["name"] = "ruby_ring_silver", 			  	["label"] = "Ruby Ring Silver", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "ruby_ring_silver.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["sapphire_ring_silver"] 		 = {["name"] = "sapphire_ring_silver", 		 	["label"] = "Sapphire Ring Silver", 	["weight"] = 200, 		["type"] = "item", 		["image"] = "sapphire_ring_silver.png", ["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["emerald_ring_silver"] 		 = {["name"] = "emerald_ring_silver", 		  	["label"] = "Emerald Ring Silver", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "emerald_ring_silver.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},

	["amethyst_ring_silver"] 				 = {["name"] = "amethyst_ring_silver", 		  	  	["label"] = "Silver Amethyst Ring", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_ring_amethyst.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["citrine_ring_silver"] 				 = {["name"] = "citrine_ring_silver", 				["label"] = "Silver Citrine Ring", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_ring_citrine.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["garnet_ring_silver"] 					 = {["name"] = "garnet_ring_silver", 			  	["label"] = "Silver Garnet Ring", 				["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_ring_garnet.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["onyx_ring_silver"] 				 	 = {["name"] = "onyx_ring_silver", 			  	  	["label"] = "Silver Onyx Ring", 				["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_ring_onyx.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["peridot_ring_silver"] 				 = {["name"] = "peridot_ring_silver", 			  	["label"] = "Silver Peridot Ring", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_ring_peridot.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["tigereye_ring_silver"] 				 = {["name"] = "tigereye_ring_silver", 			  	["label"] = "Silver Tiger`s Eye Ring", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_ring_tigerseye.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["topaz_ring_silver"] 					 = {["name"] = "topaz_ring_silver", 				["label"] = "Silver Topaz Ring", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_ring_topaz.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},

	["goldchain"] 				 	 = {["name"] = "goldchain", 			  	  	["label"] = "Golden Chain", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "goldchain.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["diamond_necklace"] 			 = {["name"] = "diamond_necklace", 			  	["label"] = "Diamond Necklace", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "diamond_necklace.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["ruby_necklace"] 				 = {["name"] = "ruby_necklace", 			  	["label"] = "Ruby Necklace", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "ruby_necklace.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["sapphire_necklace"] 			 = {["name"] = "sapphire_necklace", 			["label"] = "Sapphire Necklace", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "sapphire_necklace.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["emerald_necklace"] 			 = {["name"] = "emerald_necklace", 			  	["label"] = "Emerald Necklace", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "emerald_necklace.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},

	["amethyst_necklace"] 			 = {["name"] = "amethyst_necklace", 		  	["label"] = "Amethyst Necklace", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_necklace_amethyst.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["citrine_necklace"] 			 = {["name"] = "citrine_necklace", 			  	["label"] = "Citrine Necklace", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_necklace_citrine.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["garnet_necklace"] 			 = {["name"] = "garnet_necklace", 				["label"] = "Garnet Necklace", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_necklace_garnet.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["onyx_necklace"] 				 = {["name"] = "onyx_necklace", 			  	["label"] = "Onyx Necklace", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_necklace_onyx.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["peridot_necklace"] 			 = {["name"] = "peridot_necklace", 			  	["label"] = "Peridot Necklace", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_necklace_peridot.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["tigereye_necklace"] 			 = {["name"] = "tigereye_necklace", 		  	["label"] = "Tiger`s Eye Necklace", 	["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_necklace_tigerseye.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["topaz_necklace"] 				 = {["name"] = "topaz_necklace", 				["label"] = "Topaz Necklace", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_necklace_topaz.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},

	["rainbow_necklace"] 			 = {["name"] = "rainbow_necklace", 			  	["label"] = "Rainbow Necklace", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "rainbow_necklace.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["rainbow_necklace_silver"] 			 = {["name"] = "rainbow_necklace_silver", 			  	["label"] = "Silver Rainbow Necklace", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_necklace_rainbow.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},

	["silverchain"] 				 = {["name"] = "silverchain", 			  	 	["label"] = "Silver Chain", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "silverchain.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["diamond_necklace_silver"] 	 = {["name"] = "diamond_necklace_silver", 		["label"] = "Diamond Necklace Silver", 	["weight"] = 200, 		["type"] = "item", 		["image"] = "diamond_necklace_silver.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["ruby_necklace_silver"] 		 = {["name"] = "ruby_necklace_silver", 			["label"] = "Ruby Necklace Silver", 	["weight"] = 200, 		["type"] = "item", 		["image"] = "ruby_necklace_silver.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["sapphire_necklace_silver"] 	 = {["name"] = "sapphire_necklace_silver", 		["label"] = "Sapphire Necklace Silver", ["weight"] = 200, 		["type"] = "item", 		["image"] = "sapphire_necklace_silver.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["emerald_necklace_silver"] 	 = {["name"] = "emerald_necklace_silver", 		["label"] = "Emerald Necklace Silver", 	["weight"] = 200, 		["type"] = "item", 		["image"] = "emerald_necklace_silver.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},

	["amethyst_necklace_silver"] 			 = {["name"] = "amethyst_necklace_silver", 		  	["label"] = "Silver Amethyst Necklace", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_necklace_amethyst.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["citrine_necklace_silver"] 			 = {["name"] = "citrine_necklace_silver", 		  	["label"] = "Silver Citrine Necklace", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_necklace_citrine.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["garnet_necklace_silver"] 				 = {["name"] = "garnet_necklace_silver", 			["label"] = "Silver Garnet Necklace", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_necklace_garnet.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["onyx_necklace_silver"] 				 = {["name"] = "onyx_necklace_silver", 			  	["label"] = "Silver Onyx Necklace", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_necklace_onyx.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["peridot_necklace_silver"] 			 = {["name"] = "peridot_necklace_silver", 		  	["label"] = "Silver Peridot Necklace", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_necklace_peridot.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["tigereye_necklace_silver"] 			 = {["name"] = "tigereye_necklace_silver", 		  	["label"] = "Silver Tiger`s Eye Necklace",	 	["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_necklace_tigerseye.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["topaz_necklace_silver"] 				 = {["name"] = "topaz_necklace_silver", 			["label"] = "Silver Topaz Necklace", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_necklace_topaz.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},

	["goldearring"] 				 = {["name"] = "goldearring", 				  	["label"] = "Golden Earrings", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_earrings.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["diamond_earring"] 			 = {["name"] = "diamond_earring", 			  	["label"] = "Diamond Earrings", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "diamond_earring.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["ruby_earring"] 				 = {["name"] = "ruby_earring", 			  		["label"] = "Ruby Earrings", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "ruby_earring.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["sapphire_earring"] 			 = {["name"] = "sapphire_earring", 				["label"] = "Sapphire Earrings", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "sapphire_earring.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["emerald_earring"] 			 = {["name"] = "emerald_earring", 			  	["label"] = "Emerald Earrings", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "emerald_earring.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},

	["amethyst_earring"] 			 = {["name"] = "amethyst_earring", 			  	["label"] = "Amethyst Earrings", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_earrings_amethyst.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["citrine_earring"] 			 = {["name"] = "citrine_earring", 		  		["label"] = "Citrine Earrings", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_earrings_citrine.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["garnet_earring"] 				 = {["name"] = "garnet_earring", 				["label"] = "Garnet Earrings", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_earrings_garnet.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["onyx_earring"] 			     = {["name"] = "onyx_earring", 				  	["label"] = "Onyx Earrings", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_earrings_onyx.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["peridot_earring"] 			 = {["name"] = "peridot_earring", 			  	["label"] = "Peridot Earrings", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_earrings_peridot.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["tigereye_earring"] 			 = {["name"] = "tigereye_earring", 				["label"] = "Tiger`s Eye Earrings", 	["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_earrings_tigerseye.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["topaz_earring"] 				 = {["name"] = "topaz_earring", 				["label"] = "Topaz Earrings", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_earrings_topaz.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},

	["rainbow_earring"] 			 = {["name"] = "rainbow_earring", 			  	["label"] = "Rainbow Earrings", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "rainbow_earrings.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["rainbow_earring_silver"] 		 = {["name"] = "rainbow_earring", 			  	["label"] = "Silver Rainbow Earrings", 		["weight"] = 200, 	["type"] = "item", 		["image"] = "silver_earring_rainbow.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},

	["silverearring"] 				 = {["name"] = "silverearring", 				["label"] = "Silver Earrings", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_earring.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["diamond_earring_silver"] 		 = {["name"] = "diamond_earring_silver", 		["label"] = "Diamond Earrings Silver", 	["weight"] = 200, 		["type"] = "item", 		["image"] = "diamond_earring_silver.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["ruby_earring_silver"] 		 = {["name"] = "ruby_earring_silver", 			["label"] = "Ruby Earrings Silver", 	["weight"] = 200, 		["type"] = "item", 		["image"] = "ruby_earring_silver.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["sapphire_earring_silver"] 	 = {["name"] = "sapphire_earring_silver", 		["label"] = "Sapphire Earrings Silver", ["weight"] = 200, 		["type"] = "item", 		["image"] = "sapphire_earring_silver.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["emerald_earring_silver"] 		 = {["name"] = "emerald_earring_silver", 		["label"] = "Emerald Earrings Silver", 	["weight"] = 200, 		["type"] = "item", 		["image"] = "emerald_earring_silver.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},

	["amethyst_earring_silver"] 			 = {["name"] = "amethyst_earring_silver", 			  	["label"] = "Silver Amethyst Earrings", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_earrings_amethyst.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["citrine_earring_silver"] 				 = {["name"] = "citrine_earring_silver", 		  		["label"] = "Silver Citrine Earrings", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_earrings_citrine.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["garnet_earring_silver"] 				 = {["name"] = "garnet_earring_silver", 				["label"] = "Silver Garnet Earrings", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_earrings_garnet.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["onyx_earring_silver"] 			     = {["name"] = "onyx_earring_silver", 				  	["label"] = "Silver	Onyx Earrings", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_earrings_onyx.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["peridot_earring_silver"] 				 = {["name"] = "peridot_earring_silver", 			  	["label"] = "Silver Peridot Earrings", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_earrings_peridot.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["tigereye_earring_silver"] 			 = {["name"] = "tigereye_earring_silver", 				["label"] = "Silver Tiger`s Eye Earrings", 		["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_earrings_tigerseye.png", 		["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["topaz_earring_silver"] 				 = {["name"] = "topaz_earring_silver", 					["label"] = "Silver Topaz Earrings", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "silver_earrings_topaz.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},

	["gold_bracelet"] 				 = {["name"] = "gold_bracelet", 					["label"] = "Gold Bracelet", 			["weight"] = 200, 		["type"] = "item", 		["image"] = "gold_bracelet.png", 	["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},


	["carbon"] 					 	 = {["name"] = "carbon", 			  	  		["label"] = "Carbon", 					["weight"] = 1000, 		["type"] = "item", 		["image"] = "carbon.png", 				["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "Carbon, a base ore."},
	["ironore"] 					 = {["name"] = "ironore", 			  	  		["label"] = "Iron Ore", 				["weight"] = 1000, 		["type"] = "item", 		["image"] = "ironore.png", 				["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "Iron, a base ore."},
	["copperore"] 					 = {["name"] = "copperore", 			  	  	["label"] = "Copper Ore", 				["weight"] = 1000, 		["type"] = "item", 		["image"] = "copperore.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "Copper, a base ore."},
	["goldore"] 					 = {["name"] = "goldore", 			  	  		["label"] = "Gold Ore", 				["weight"] = 1000, 		["type"] = "item", 		["image"] = "goldore.png", 				["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "Gold Ore"},
	["silverore"] 					 = {["name"] = "silverore", 			  	  	["label"] = "Silver Ore", 				["weight"] = 1000, 		["type"] = "item", 		["image"] = "silverore.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "Silver Ore"},

	["goldingot"] 					 = {["name"] = "goldingot", 			  	  	["label"] = "Gold Ingot", 				["weight"] = 1000, 		["type"] = "item", 		["image"] = "goldingot.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},
	["silveringot"] 				 = {["name"] = "silveringot", 			  	  	["label"] = "Silver Ingot", 			["weight"] = 1000, 		["type"] = "item", 		["image"] = "silveringot.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = ""},

	["drillbit"] 					 = {["name"] = "drillbit", 			  	  		["label"] = "Drill Bit", 				["weight"] = 10, 		["type"] = "item", 		["image"] = "drillbit.png", 			["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "" },

	["goldpan"] 					 = {["name"] = "goldpan", 			  	  		["label"] = "Gold Panning Tray", 		["weight"] = 10, 		["type"] = "item", 		["image"] = "goldpan.png", 				["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "" },

	["bottle"] 						 = {["name"] = "bottle", 			  	  		["label"] = "Empty Bottle", 			["weight"] = 10, 		["type"] = "item", 		["image"] = "bottle.png", 				["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "A glass bottle"},
	["can"] 						 = {["name"] = "can", 			  	  			["label"] = "Empty Can", 				["weight"] = 10, 		["type"] = "item", 		["image"] = "can.png", 					["unique"] = false, 	["useable"] = false, 	["shouldClose"] = false, ["combinable"] = nil,   ["description"] = "An empty can, good for recycling"},

}

Crafting = {
	SmeltMenu = {
		{ ["copper"] = { ["copperore"] = 1 }, ['amount'] = 4 },
		{ ["copperbar"] = { ["copperore"] = 1 }, ['amount'] = 2 },
		{ ["brass"] = { ["copperbar"] = 1 }, ['amount'] = 4 },
		{ ["goldingot"] = { ["goldore"] = 1 } },
		{ ["goldingot"] = { ["goldchain"] = 3 } },
		{ ["goldingot"] = { ["gold_ring"] = 4 } },
		{ ["silveringot"] = { ["silverore"] = 1 } },
		{ ["silveringot"] = { ["silverchain"] = 3 } },
		{ ["silveringot"] = { ["silver_ring"] = 4 } },
		{ ["iron"] = { ["ironore"] = 1 } },
		{ ["leadbar"] = { ["leadore"] = 1 } },
		{ ["lead"] = { ["leadbar"] = 4 } },
		{ ["steel"] = { ["ironore"] = 1, ["carbon"] = 1 } },
		{ ["aluminum"] = { ["can"] = 2, }, ['amount'] = 3 },
		{ ["glass"] = { ["bottle"] = 2, }, ['amount'] = 2 },
		{ ["blasticplate"] = { ["steel"] = 100, }, ['amount'] = 1},
	},
	GemCut = {
		{ ["emerald"] = { ["uncut_emerald"] = 1, } },
		{ ["diamond"] = { ["uncut_diamond"] = 1}, },
		{ ["ruby"] = { ["uncut_ruby"] = 1 }, },
		{ ["sapphire"] = { ["uncut_sapphire"] = 1 }, },
		{ ["amethyst"] = { ["uncut_amethyst"] = 1, } },
		{ ["citrine"] = { ["uncut_citrine"] = 1}, },
		{ ["garnet"] = { ["uncut_garnet"] = 1 }, },
		{ ["onyx"] = { ["uncut_onyx"] = 1 }, },
		{ ["peridot"] = { ["uncut_peridot"] = 1, } },
		{ ["tigereye"] = { ["uncut_tigereye"] = 1}, },
		{ ["topaz"] = { ["uncut_topaz"] = 1 }, },

	},
	RingCut = {
		{ ["gold_ring"] = { ["goldingot"] = 1 }, ['amount'] = 3 },
		{ ["silver_ring"] = { ["silveringot"] = 1 }, ['amount'] = 3 },
		{ ["diamond_ring"] = { ["gold_ring"] = 1, ["diamond"] = 1 }, },
		{ ["emerald_ring"] = { ["gold_ring"] = 1, ["emerald"] = 1 }, },
		{ ["ruby_ring"] = { ["gold_ring"] = 1, ["ruby"] = 1 }, },
		{ ["sapphire_ring"] = { ["gold_ring"] = 1, ["sapphire"] = 1 }, },
		
		{ ["amethyst_ring"] = { ["gold_ring"] = 1, ["amethyst"] = 1 }, },
		{ ["citrine_ring"] = { ["gold_ring"] = 1, ["citrine"] = 1 }, },
		{ ["garnet_ring"] = { ["gold_ring"] = 1, ["garnet"] = 1 }, },
		{ ["onyx_ring"] = { ["gold_ring"] = 1, ["onyx"] = 1 }, },
		{ ["peridot_ring"] = { ["gold_ring"] = 1, ["peridot"] = 1 }, },
		{ ["tigereye_ring"] = { ["gold_ring"] = 1, ["tigereye"] = 1 }, },
		{ ["topaz_ring"] = { ["gold_ring"] = 1, ["topaz"] = 1 }, },
		
		{ ["diamond_ring_silver"] = { ["silver_ring"] = 1, ["diamond"] = 1 }, },
		{ ["emerald_ring_silver"] = { ["silver_ring"] = 1, ["emerald"] = 1 }, },
		{ ["ruby_ring_silver"] = { ["silver_ring"] = 1, ["ruby"] = 1 }, },
		{ ["sapphire_ring_silver"] = { ["silver_ring"] = 1, ["sapphire"] = 1 }, },
		
		{ ["amethyst_ring_silver"] = { ["silver_ring"] = 1, ["amethyst"] = 1 }, },
		{ ["citrine_ring_silver"] = { ["silver_ring"] = 1, ["citrine"] = 1 }, },
		{ ["garnet_ring_silver"] = { ["silver_ring"] = 1, ["garnet"] = 1 }, },
		{ ["onyx_ring_silver"] = { ["silver_ring"] = 1, ["onyx"] = 1 }, },
		{ ["peridot_ring_silver"] = { ["silver_ring"] = 1, ["peridot"] = 1 }, },
		{ ["tigereye_ring_silver"] = { ["silver_ring"] = 1, ["tigereye"] = 1 }, },
		{ ["topaz_ring_silver"] = { ["silver_ring"] = 1, ["topaz"] = 1 }, },
	
		{ ["rainbow_ring"] = { ["gold_ring"] = 1, ["sapphire"] = 1, ["emerald"] = 1, ["ruby"] = 1, ["diamond"] = 1, ["amethyst"] = 1, ["citrine"] = 1, ["garnet"] = 1, ["onyx"] = 1, ["peridot"] = 1, ["tigereye"] = 1, ["topaz"] = 1 }, },
		{ ["rainbow_ring_silver"] = { ["silver_ring"] = 1, ["sapphire"] = 1, ["emerald"] = 1, ["ruby"] = 1, ["diamond"] = 1, ["amethyst"] = 1, ["citrine"] = 1, ["garnet"] = 1, ["onyx"] = 1, ["peridot"] = 1, ["tigereye"] = 1, ["topaz"] = 1 }, },
	},
	NeckCut = {
		{ ["goldchain"] = { ["goldingot"] = 1 }, ['amount'] = 3  },
		{ ["silverchain"] = { ["silveringot"] = 1 }, ['amount'] = 3  },
		{ ["diamond_necklace"] = { ["goldchain"] = 1, ["diamond"] = 1 }, },
		{ ["ruby_necklace"] = { ["goldchain"] = 1, ["ruby"] = 1 }, },
		{ ["sapphire_necklace"] = { ["goldchain"] = 1, ["sapphire"] = 1 }, },
		{ ["emerald_necklace"] = { ["goldchain"] = 1, ["emerald"] = 1 }, },
		
		{ ["amethyst_necklace"] = { ["goldchain"] = 1, ["amethyst"] = 1 }, },
		{ ["citrine_necklace"] = { ["goldchain"] = 1, ["citrine"] = 1 }, },
		{ ["garnet_necklace"] = { ["goldchain"] = 1, ["garnet"] = 1 }, },
		{ ["onyx_necklace"] = { ["goldchain"] = 1, ["onyx"] = 1 }, },
		{ ["peridot_necklace"] = { ["goldchain"] = 1, ["peridot"] = 1 }, },
		{ ["tigereye_necklace"] = { ["goldchain"] = 1, ["tigereye"] = 1 }, },
		{ ["topaz_necklace"] = { ["goldchain"] = 1, ["topaz"] = 1 }, },
		
		{ ["diamond_necklace_silver"] = { ["silverchain"] = 1, ["diamond"] = 1 }, },
		{ ["ruby_necklace_silver"] = { ["silverchain"] = 1, ["ruby"] = 1 }, },
		{ ["sapphire_necklace_silver"] = { ["silverchain"] = 1, ["sapphire"] = 1 }, },
		{ ["emerald_necklace_silver"] = { ["silverchain"] = 1, ["emerald"] = 1 }, },
		
		{ ["amethyst_necklace_silver"] = { ["silverchain"] = 1, ["amethyst"] = 1 }, },
		{ ["citrine_necklace_silver"] = { ["silverchain"] = 1, ["citrine"] = 1 }, },
		{ ["garnet_necklace_silver"] = { ["silverchain"] = 1, ["garnet"] = 1 }, },
		{ ["onyx_necklace_silver"] = { ["silverchain"] = 1, ["onyx"] = 1 }, },
		{ ["peridot_necklace_silver"] = { ["silverchain"] = 1, ["peridot"] = 1 }, },
		{ ["tigereye_necklace_silver"] = { ["silverchain"] = 1, ["tigereye"] = 1 }, },
		{ ["topaz_necklace_silver"] = { ["silverchain"] = 1, ["topaz"] = 1 }, },

		{ ["rainbow_necklace"] = { ["goldchain"] = 1, ["sapphire"] = 1, ["emerald"] = 1, ["ruby"] = 1, ["diamond"] = 1, ["amethyst"] = 1, ["citrine"] = 1, ["garnet"] = 1, ["onyx"] = 1, ["peridot"] = 1, ["tigereye"] = 1, ["topaz"] = 1 }, },
		{ ["rainbow_necklace_silver"] = { ["silverchain"] = 1, ["sapphire"] = 1, ["emerald"] = 1, ["ruby"] = 1, ["diamond"] = 1, ["amethyst"] = 1, ["citrine"] = 1, ["garnet"] = 1, ["onyx"] = 1, ["peridot"] = 1, ["tigereye"] = 1, ["topaz"] = 1 }, },
	},
	EarCut = {
		{ ["goldearring"] = { ["goldingot"] = 1 }, ['amount'] = 3  },
		{ ["silverearring"] = { ["silveringot"] = 1 }, ['amount'] = 3  },
		{ ["diamond_earring"] = { ["goldearring"] = 1, ["diamond"] = 1 }, },
		{ ["ruby_earring"] = { ["goldearring"] = 1, ["ruby"] = 1 }, },
		{ ["sapphire_earring"] = { ["goldearring"] = 1, ["sapphire"] = 1 }, },
		{ ["emerald_earring"] = { ["goldearring"] = 1, ["emerald"] = 1 }, },
		
		{ ["amethyst_earring"] = { ["goldearring"] = 1, ["amethyst"] = 1 }, },
		{ ["citrine_earring"] = { ["goldearring"] = 1, ["citrine"] = 1 }, },
		{ ["garnet_earring"] = { ["goldearring"] = 1, ["garnet"] = 1 }, },
		{ ["onyx_earring"] = { ["goldearring"] = 1, ["onyx"] = 1 }, },
		{ ["peridot_earring"] = { ["goldearring"] = 1, ["peridot"] = 1 }, },
		{ ["tigereye_earring"] = { ["goldearring"] = 1, ["tigereye"] = 1 }, },
		{ ["topaz_earring"] = { ["goldearring"] = 1, ["topaz"] = 1 }, },
		
		{ ["diamond_earring_silver"] = { ["silverearring"] = 1, ["diamond"] = 1 }, },
		{ ["ruby_earring_silver"] = { ["silverearring"] = 1, ["ruby"] = 1 }, },
		{ ["sapphire_earring_silver"] = { ["silverearring"] = 1, ["sapphire"] = 1 }, },
		{ ["emerald_earring_silver"] = { ["silverearring"] = 1, ["emerald"] = 1 }, },
		
		{ ["amethyst_earring_silver"] = { ["silverearring"] = 1, ["amethyst"] = 1 }, },
		{ ["citrine_earring_silver"] = { ["silverearring"] = 1, ["citrine"] = 1 }, },
		{ ["garnet_earring_silver"] = { ["silverearring"] = 1, ["garnet"] = 1 }, },
		{ ["onyx_earring_silver"] = { ["silverearring"] = 1, ["onyx"] = 1 }, },
		{ ["peridot_earring_silver"] = { ["silverearring"] = 1, ["peridot"] = 1 }, },
		{ ["tigereye_earring_silver"] = { ["silverearring"] = 1, ["tigereye"] = 1 }, },
		{ ["topaz_earring_silver"] = { ["silverearring"] = 1, ["topaz"] = 1 }, },
	
		{ ["rainbow_earring"] = { ["goldearring"] = 1, ["sapphire"] = 1, ["emerald"] = 1, ["ruby"] = 1, ["diamond"] = 1, ["amethyst"] = 1, ["citrine"] = 1, ["garnet"] = 1, ["onyx"] = 1, ["peridot"] = 1, ["tigereye"] = 1, ["topaz"] = 1 }, },
		{ ["rainbow_earring_silver"] = { ["silverearring"] = 1, ["sapphire"] = 1, ["emerald"] = 1, ["ruby"] = 1, ["diamond"] = 1, ["amethyst"] = 1, ["citrine"] = 1, ["garnet"] = 1, ["onyx"] = 1, ["peridot"] = 1, ["tigereye"] = 1, ["topaz"] = 1 }, },
	},
}

	SellItems = { -- Selling Prices
		['copperore'] = 200,
		['goldore'] = 300,
		['silverore'] = 140,
		['ironore'] = 200,
		['carbon'] = 50,

		['goldingot'] = 500,
		['silveringot'] = 400,

		['uncut_emerald'] = 700,
		['uncut_ruby'] = 800,
		['uncut_diamond'] = 900,
		['uncut_sapphire'] = 600,
		['uncut_amethyst'] = 700,
		['uncut_citrine'] = 800,
		['uncut_garnet'] = 900,
		['uncut_onyx'] = 600,
		['uncut_peridot'] = 700,
		['uncut_tigereye'] = 800,
		['uncut_topaz'] = 900,

		['emerald'] = 1000,
		['ruby'] = 1000,
		['diamond'] = 1000,
		['sapphire'] = 1000,
		['amethyst'] = 1000,
		['citrine'] = 1000,
		['garnet'] = 1000,
		['onyx'] = 1100,
		['peridot'] = 1000,
		['tigereye'] = 1000,
		['topaz'] = 1000,

		
		['diamond_ring'] = 3000,
		['emerald_ring'] = 3400,
		['ruby_ring'] = 3500,
		['sapphire_ring'] = 3700,
	
		['diamond_ring_silver'] = 1200,
		['emerald_ring_silver'] = 1100,
		['ruby_ring_silver'] = 1200,
		['sapphire_ring_silver'] = 1900,

		['diamond_necklace'] = 3900,
		['emerald_necklace'] = 3200,
		['ruby_necklace'] = 3900,
		['sapphire_necklace'] = 3800,
	
		['diamond_necklace_silver'] = 2600,
		['emerald_necklace_silver'] = 2400,
		['ruby_necklace_silver'] = 2200,
		['sapphire_necklace_silver'] = 2400,

		['diamond_earring'] = 3800,
		['emerald_earring'] = 3200,
		['ruby_earring'] = 3600,
		['sapphire_earring'] = 3700,
	
		['diamond_earring_silver'] = 2300,
		['emerald_earring_silver'] = 3600,
		['ruby_earring_silver'] = 2500,
		['sapphire_earring_silver'] = 2100,

		['gold_ring'] = 1000,
		['goldchain'] = 900,
		['goldearring'] = 700,
		['silver_ring'] = 600,
		['silverchain'] = 400,
		['silverearring'] = 400,

		--Extra jewelery
		['amethyst_earring'] = 3800,
		['citrine_earring'] = 3200,
		['garnet_earring'] = 3600,
		['onyx_earring'] = 3700,
		['peridot_earring'] = 3400,
		['tigereye_earring'] = 3200,
		['topaz_earring'] = 3300,

		['amethyst_earring_silver'] = 2800,
		['citrine_earring_silver'] = 2200,
		['garnet_earring_silver'] = 2600,
		['onyx_earring_silver'] = 2700,
		['peridot_earring_silver'] = 2400,
		['tigereye_earring_silver'] = 2200,
		['topaz_earring_silver'] = 2300,

		['amethyst_necklace'] = 3800,
		['citrine_necklace'] = 3200,
		['garnet_necklace'] = 3200,
		['onyx_necklace'] = 3700,
		['peridot_necklace'] = 3400,
		['tigereye_necklace'] = 3200,
		['topaz_necklace'] = 3300,

		['amethyst_necklace_silver'] = 2800,
		['citrine_necklace_silver'] = 2200,
		['garnet_necklace_silver'] = 2600,
		['onyx_necklace_silver'] = 2700,
		['peridot_necklace_silver'] = 2400,
		['tigereye_necklace_silver'] = 2200,
		['topaz_necklace_silver'] = 2300,

		['amethyst_ring'] = 3800,
		['citrine_ring'] = 3200,
		['garnet_ring'] = 3600,
		['onyx_ring'] = 3700,
		['peridot_ring'] = 3400,
		['tigereye_ring'] = 3200,
		['topaz_ring'] = 3300,

		['amethyst_ring_silver'] = 2800,
		['citrine_ring_silver'] = 2700,
		['garnet_ring_silver'] = 2690,
		['onyx_ring_silver'] = 2700,
		['peridot_ring_silver'] = 2400,
		['tigereye_ring_silver'] = 2200,
		['topaz_ring_silver'] = 2300,

		['rainbow_necklace'] = 5700,
		['rainbow_ring'] = 5500,
		['rainbow_earring'] = 5400,
		
		['rainbow_necklace_silver'] = 4700,
		['rainbow_ring_silver'] = 4500,
		['rainbow_earring_silver'] = 4400,
	},
	
	WashPool = {
		"goldore",
		"uncut_ruby",
		"uncut_emerald",
		"uncut_diamond",
		"uncut_sapphire",
		"uncut_amethyst",
		"uncut_citrine",
		"uncut_garnet",
		"uncut_onyx",
		"uncut_peridot",
		"uncut_tigereye",
		"uncut_topaz",
		"goldore",
	},